### ISSUE TITLE
attributeerror

### ISSUE THREAD

**Issue by Almenon** [Almenon/reddit_episode_bot#26]
```
Jul 14 22:16:04 obscure-peak-2895 app/worker.1: INFO:root:analyzing https://www.reddit.com/r/BoJackHorseman/comments/hr8tv2/rewatching_s1ep1_and_bojack_has_a_panic_attack/
Jul 14 22:16:04 obscure-peak-2895 app/worker.1: INFO:root:request: Rewatching S1-EP1, and Bojack has a panic attack from the prospect of making a phone call. RELATABLE. 💀
Jul 14 22:16:04 obscure-peak-2895 app/worker.1: INFO:root:Parsed request is http://www.omdbapi.com/?apikey=&t=bojack%20horseman&Season=1&Episode=1
Jul 14 22:16:04 obscure-peak-2895 app/worker.1: DEBUG:root:{"Title":"BoJack Horseman: The BoJack Horseman Story, Chapter One","Year":"2014","Rated":"N/A","Released":"22 Aug 2014","Season":"1","Episode":"1","Runtime":"25 min","Genre":"Animation, Comedy, Drama","Director":"Joel Moser","Writer":"Raphael Bob-Waksberg (created by), Raphael Bob-Waksberg","Actors":"Will Arnett, Amy Sedaris, Alison Brie, Paul F. Tompkins","Plot":"A publishing house eagerly awaits BoJack's memoirs, but he hasn't even started yet. His agent/ex and his publisher try to talk him into working with a ghost writer, but BoJack's too despondent about being washed up to focus.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://m.media-amazon.com/images/M/MV5BMjI1MDQ3MzMzNF5BMl5BanBnXkFtZTgwMDE4ODM5MTE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.1/10"}],"Metascore":"N/A","imdbRating":"7.1","imdbVotes":"2522","imdbID":"tt3957774","seriesID":"tt3398228","Type":"episode","Response":"True"}
Jul 14 22:16:04 obscure-peak-2895 app/worker.1: INFO:root:JSON: {'Title': 'BoJack Horseman: The BoJack Horseman Story, Chapter One', 'Year': '2014', 'Rated': 'N/A', 'Released': '22 Aug 2014', 'Season': '1', 'Episode': '1', 'Runtime': '25 min', 'Genre': 'Animation, Comedy, Drama', 'Director': 'Joel Moser', 'Writer': 'Raphael Bob-Waksberg (created by), Raphael Bob-Waksberg', 'Actors': 'Will Arnett, Amy Sedaris, Alison Brie, Paul F. Tompkins', 'Plot': "A publishing house eagerly awaits BoJack's memoirs, but he hasn't even started yet. His agent/ex and his publisher try to talk him into working with a ghost writer, but BoJack's too despondent about being washed up to focus.", 'Language': 'English', 'Country': 'USA', 'Awards': 'N/A', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMjI1MDQ3MzMzNF5BMl5BanBnXkFtZTgwMDE4ODM5MTE@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.1/10'}], 'Metascore': 'N/A', 'imdbRating': '7.1', 'imdbVotes': '2522', 'imdbID': 'tt3957774', 'seriesID': 'tt3398228', 'Type': 'episode', 'Response': 'True'}
Jul 14 22:16:06 obscure-peak-2895 app/worker.1: ERROR:root:can't set attribute
Jul 14 22:16:06 obscure-peak-2895 app/worker.1: Traceback (most recent call last):
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "heroku_timing.py", line 22, in <module>
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     bot.scan(last_time)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/bot.py", line 88, in scan
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     check_subreddits(last_scan)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/bot.py", line 112, in check_subreddits
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     submission.add_comment(answer)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/praw/objects.py", line 1187, in add_comment
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     response = self.reddit_session._add_comment(self.fullname, text)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/praw/__init__.py", line 2669, in _add_comment
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     retval = decorator(add_comment_helper)(self, thing_id, text)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/praw/decorators.py", line 271, in wrap
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     return function(*args, **kwargs)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/praw/__init__.py", line 2662, in add_comment_helper
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "<decorator-gen-8>", line 2, in request_json
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/praw/decorators.py", line 116, in raise_api_exceptions
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/praw/__init__.py", line 632, in request_json
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     data = json.loads(response, object_hook=hook)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/json/__init__.py", line 367, in loads
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/json/decoder.py", line 339, in decode
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/json/decoder.py", line 355, in raw_decode
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     obj, end = self.scan_once(s, idx)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/praw/__init__.py", line 490, in _json_reddit_objecter
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     return object_class.from_api_response(self, json_data['data'])
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/praw/objects.py", line 55, in from_api_response
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     return cls(reddit_session, json_dict=json_dict)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     underscore_names=['replies'])
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/praw/objects.py", line 70, in __init__
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     self._has_fetched = self._populate(json_dict, fetch)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:     setattr(self, name, value)
Jul 14 22:16:06 obscure-peak-2895 app/worker.1:   File "/app/.heroku/python/lib/python3.6/site-packages/praw/objects.py", line 127, in __setattr__
Jul 14 22:16:06 obscure-peak-2895 app/worker.1: AttributeError: can't set attribute
```

**Comment by Almenon** [comment]
related to https://github.com/Almenon/reddit_episode_bot/issues/12
